## Web-Scraping no Site da Anbima

### Objetivo: Armazenar todas as Datas de Feriados Nacionais.

In [1]:
# Instalando a biblioteca Selenium: 
# !pip install selenium

In [2]:
# Importando as bibliotecas necessárias:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd

# Abrindo o site da Anbima:
driver = webdriver.Chrome()
driver.get("https://www.anbima.com.br/feriados/")

# Baixando a planilha com todos os feriados:
elementos = driver.find_element(By.XPATH, '//*[@id="cinza50"]/div/table[2]/tbody/tr[1]/td/strong/a')
elementos.click()

# Armazenando os dados da planilha em um dataframe: 
df = pd.read_excel(r'C:\Users\Wanderson\Downloads\feriados_nacionais.xls')
display(df)

,Data,Dia da Semana,Feriado
0,2001-01-01 00:00:00,segunda-feira,Confraternização Universal
1,2001-02-26 00:00:00,segunda-feira,Carnaval
2,2001-02-27 00:00:00,terça-feira,Carnaval
3,2001-04-13 00:00:00,sexta-feira,Paixão de Cristo
4,2001-04-21 00:00:00,sábado,Tiradentes
...,...,...,...
940,"2) A lei nº 9.504/97 estabeleceu que, em ano e...",NaN,NaN
941,NaN,NaN,NaN
942,"3) De acordo com a Resolução nº 2.596/99, no ú...",NaN,NaN
943,NaN,NaN,NaN
944,4) Esta listagem não inclui os feriados munici...,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Data           941 non-null    object
 1   Dia da Semana  936 non-null    object
 2   Feriado        936 non-null    object
dtypes: object(3)
memory usage: 22.3+ KB